const express = require('express');
const { z } = require('zod');
const oracledb = require('oracledb');

const { withConn } = require('../db');
const { requireAuth } = require('../middleware/requireAuth');
const { requireRole } = require('../middleware/requireRole');

const bookingRoutes = express.Router();

const createBookingSchema = z.object({
  id: z.string().min(1), // uuid string generated by client/server
  client_id: z.string().min(1),
  coach_id: z.string().min(1),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  time: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),
});

// Create booking (pending)
bookingRoutes.post('/', requireAuth, requireRole('client'), async (req, res, next) => {
  try {
    const body = createBookingSchema.parse(req.body);
    if (req.user?.sub !== body.client_id) return res.status(403).json({ error: 'Forbidden' });
    await withConn(async (conn) => {
      await conn.execute(
        `INSERT INTO bookings (id, client_id, coach_id, booking_date, time_hhmm, status)
         VALUES (:id, :client_id, :coach_id, TO_DATE(:d,'YYYY-MM-DD'), :t, 'pending')`,
        { id: body.id, client_id: body.client_id, coach_id: body.coach_id, d: body.date, t: body.time },
        { autoCommit: true }
      );
    });
    return res.status(201).json({ ok: true });
  } catch (e) {
    if (e instanceof oracledb.Error) {
      // Unique / constraint errors become 409
      const msg = String(e.message || '');
      if (msg.includes('ORA-00001')) return res.status(409).json({ error: 'Slot already booked' });
    }
    return next(e);
  }
});

// List bookings for a coach in date range (simple)
bookingRoutes.get('/coach', requireAuth, requireRole('coach'), async (req, res, next) => {
  try {
    const coachId = String(req.query.coachId || '').trim();
    const from = String(req.query.from || '').trim();
    const to = String(req.query.to || '').trim();
    if (!coachId) return res.status(400).json({ error: 'Missing coachId' });
    if (req.user?.sub !== coachId) return res.status(403).json({ error: 'Forbidden' });
    if (!/^\d{4}-\d{2}-\d{2}$/.test(from) || !/^\d{4}-\d{2}-\d{2}$/.test(to)) {
      return res.status(400).json({ error: 'from/to must be YYYY-MM-DD' });
    }

    const rows = await withConn(async (conn) => {
      const r = await conn.execute(
        `SELECT id, client_id, coach_id, TO_CHAR(booking_date,'YYYY-MM-DD') AS date, time_hhmm AS time, status, created_at
         FROM bookings
         WHERE coach_id = :coach_id
           AND booking_date BETWEEN TO_DATE(:from_d,'YYYY-MM-DD') AND TO_DATE(:to_d,'YYYY-MM-DD')
         ORDER BY created_at DESC`,
        { coach_id: coachId, from_d: from, to_d: to },
        { outFormat: oracledb.OUT_FORMAT_OBJECT }
      );
      return r.rows || [];
    });

    return res.json({ rows });
  } catch (e) {
    return next(e);
  }
});

module.exports = { bookingRoutes };

