# Copies API (and optional coach id) from frontend/.env into Flutter assets/app.env
# so Flutter uses the same backend URL as Expo without manual copy/paste.

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$src = Join-Path $root "frontend\.env"
$dst = Join-Path $root "assets\app.env"

if (-not (Test-Path $src)) {
  Write-Error "Missing $src - create frontend/.env from frontend/.env.example first."
}

$map = @{}
Get-Content $src | ForEach-Object {
  $line = $_.Trim()
  if ($line -match '^\s*#' -or $line -eq '') { return }
  if ($line -match '^([^=]+)=(.*)$') {
    $map[$matches[1].Trim()] = $matches[2].Trim()
  }
}

$api = $map['EXPO_PUBLIC_API_BASE_URL']
if (-not $api) { $api = 'http://10.0.2.2:4000' }

$coach = $map['EXPO_PUBLIC_DEFAULT_COACH_ID']
if (-not $coach) { $coach = '' }

$lines = @(
  '# Generated by scripts/sync_env_from_frontend.ps1. Edit frontend/.env and re-run to refresh.',
  'USE_BACKEND=true',
  "API_BASE_URL=$api",
  "DEFAULT_COACH_ID=$coach",
  '',
  '# Duplicate Expo key name for convenience.',
  "EXPO_PUBLIC_DEFAULT_COACH_ID=$coach"
)

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($dst, ($lines -join "`n"), $utf8)
Write-Host "Wrote $dst"
Write-Host "API_BASE_URL=$api"
Write-Host "DEFAULT_COACH_ID=$coach"
